name: nfc_manager
description: A Flutter plugin for accessing the NFC features on Android and iOS.
version: 4.0.0-dev
repository: https://github.com/okadan/flutter-nfc-manager
publish_to: 'none' # TODO: remove this line

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  ndef_record:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints:
  pigeon:

flutter:
  plugin:
    platforms:
      android:
        package: dev.flutter.plugins.nfcmanager
        pluginClass: NfcManagerPlugin
      ios:
        pluginClass: NfcManagerPlugin
